version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
